(function(){
  'use strict';
  const state={juegos:[], resumen:{}};
  const $=id=>document.getElementById(id);
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const img=j=>j.imagen||'imagenes/logo.png';
  function tarjeta(j){return `<article class="explorar-card"><a href="juego.html?id=${encodeURIComponent(j.id)}"><div class="explorar-card-img"><img loading="lazy" src="${esc(img(j))}" alt="${esc(j.nombre)}"></div><div class="explorar-card-meta"><strong>${esc(j.nombre)}</strong><span>${esc(j.categoria||'Juegos')}</span></div></a></article>`}
  function render(id,items){const el=$(id);if(!el)return;el.innerHTML=items.length?items.slice(0,8).map(tarjeta).join(''):'<div class="explorar-vacio">No hay juegos para mostrar todavía.</div>';}
  async function resumen(){try{const r=await fetch('/api/content?action=games-overview');const d=await r.json();if(d&&d.success)state.resumen=d.juegos||{};}catch(_){} }
  function rank(field){return state.juegos.slice().sort((a,b)=>{const av=Number((state.resumen[String(a.id)]||{})[field]||0),bv=Number((state.resumen[String(b.id)]||{})[field]||0);if(bv!==av)return bv-av;return Number(b.id||0)-Number(a.id||0);});}
  function renderCats(){const el=$('explorarCategorias');if(!el)return;const cats=[...new Set(state.juegos.map(j=>j.categoria).filter(Boolean))].slice(0,12);el.innerHTML=cats.map(c=>`<button class="explorar-chip" type="button" data-cat="${esc(c)}">${esc(c)}</button>`).join('');el.querySelectorAll('[data-cat]').forEach(b=>b.addEventListener('click',()=>location.href='juegos.html?categoria='+encodeURIComponent(b.dataset.cat)));}
  async function amigos(){const el=$('explorarAmigos');if(!el)return;const u=typeof window.MRSession==='object'?window.MRSession.get():(()=>{try{return JSON.parse(localStorage.getItem('usuarioActivo')||'null')}catch(_){return null}})();if(!u||!u.nombre){el.innerHTML='<div class="explorar-vacio">Iniciá sesión para ver qué están jugando tus amigos.</div>';return;}try{const r=await fetch('/api/social?action=friends&username='+encodeURIComponent(u.nombre));const d=await r.json();const lista=(d&&d.success?d.amigos:[])||[];if(!lista.length){el.innerHTML='<div class="explorar-vacio">Todavía no tenés amigos agregados.</div>';return;}el.innerHTML=lista.slice(0,6).map(a=>{const av=a.avatar||null;let ah='<span>👤</span>';if(typeof avatarMiniaturaHTML==='function'&&av)ah=avatarMiniaturaHTML(av);return `<div class="explorar-amigo"><div class="explorar-amigo-main"><div class="explorar-amigo-avatar">${ah}</div><div><strong>@${esc(a.username)}</strong><span>⭐ Nivel ${esc(a.level||1)} · ${Number(a.xp||0).toLocaleString('es-AR')} XP</span></div></div><a href="usuario.html?usuario=${encodeURIComponent(a.username)}">Ver</a></div>`}).join('');}catch(_){el.innerHTML='<div class="explorar-vacio">No pudimos cargar tus amigos ahora.</div>';}}
  function buscar(){const q=($('explorarBuscar').value||'').trim();if(q)location.href='juegos.html?q='+encodeURIComponent(q);}
  function init(){state.juegos=Array.isArray(window.juegos)?window.juegos:[];renderCats();render('explorarTrending',rank('tendencia'));render('explorarNuevos',state.juegos.slice().sort((a,b)=>Number(b.id||0)-Number(a.id||0)));resumen().then(()=>{render('explorarTrending',rank('tendencia'));});amigos();$('explorarBuscarBtn')?.addEventListener('click',buscar);$('explorarBuscar')?.addEventListener('keydown',e=>{if(e.key==='Enter')buscar()});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
